apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginxweb
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginxweb
  minReplicas: 1
  maxReplicas: 13
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
