apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxweb
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxweb
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginxweb
        purpose: wordpress
        tier : frontend
    spec:
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10014
        # ServiceAccountToken are the keys to access the cluster, we prevent them from being obtained by an attack on the container shell.
        automountServiceAccountToken: false
      containers:
        - image: 1.21.6-alpine
          imagePullPolicy: Always
          name: webservice
          envFrom:
          - configMapRef:
              name: nginxweb-vars
          ports:
            - containerPort: 80
              protocol: TCP
              name: http-port
            - containerPort: 443
              protocol: TCP
              name: https-port
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "[ -f /run/nginx.pid ] && ps -A | grep nginx"
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /index.html
              port: 443
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            capabilities:
              drop:
                - NET_RAW
